name: Refresh XLWebServices
on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    name: Refresh Web Services
    runs-on: ubuntu-latest
    steps:
      - name: Clear Web Services cache
        run: curl -X POST --fail https://aonyx.ffxiv.wang/Proxy/ClearCache?key=${{ secrets.CACHE_CLEAR_KEY }}
